# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='p_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='r_name',
            field=models.CharField(max_length=10),
        ),
    ]
