# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180425_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='r',
        ),
        migrations.AddField(
            model_name='user',
            name='u',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role'),
        ),
    ]
