# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180425_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role'),
        ),
    ]
